name: iOS Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 30
    concurrency:
      group: ios-tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0'

      - name: Xcode version
        run: xcodebuild -version

      - name: Build and test (iOS Simulator)
        run: |
          set -euo pipefail
          xcodebuild \
            -project ComfySpaces.xcodeproj \
            -scheme ComfySpaces \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            test

