name: iOS Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Xcode Unit Tests
    runs-on: macos-15
    timeout-minutes: 30
    concurrency:
      group: ios-tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Clean DerivedData (just in case)
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Xcode version
        run: xcodebuild -version

      - name: Build and test (iOS Simulator)
        run: |
          set -euo pipefail
          xcodebuild test \
          -scheme ComfySpacesTests.xcodeproj \
          -project ComfySpaces.xcodeproj \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
          -enableCodeCoverage YES | xcpretty

